name: yaraos_shell_desktop
description: "Shell wallpaper applet for YaraOS"

publish_to: none
homepage: https://softyes.com.br
repository: https://github.com/yara-os/shell

version: 0.1.0+1
resolution: workspace

environment:
  sdk: ^3.11.1
  flutter: ^3.41.4

dependencies:
  flutter:
    sdk: flutter

  wayland_layer_shell: ^1.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
